---
main: inc.xiddy.hypixel.Main
name: Hypixel
author: xiddy
version: 1.0
description: "A replica of many Hypixel games and their server structure."
depend: [Citizens]
commands:
  ping:
    description: "Ping the server to see your connection."
    usage: "Usage: /<command>"
  startgame:
    description: "Start a new game."
    usage: "Usage: /<command> <game_name>"
  stopgame:
    description: "Stop the current game you are in."
    usage: "Usage: /<command>"
  setupbedwars:
    description: "Setup a game of bedwars."
    usage: "Usage: /<command> <setgen:setitemshop:setteamshop:setbed:setrespawn:setdiamondgen#:setemeraldgen1#> <team_color:global>"
  savelocation:
    description: "Saves a location to be used later."
    usage: "Usage: /<command>"
  perms:
    description: "Updates a player's permissions."
    usage: "Usage: /<command> <player>"
  setvelocity:
    description: "Sets the current player's velocity."
    usage: "Usage: /<command> <x_velocity> <y_velocity> <z_velocity>"
